name = "OmniPackage"
uuid = "992a9bcd-042f-40bc-a011-a3ea62fdd9b8"
authors = ["Chris Elrod <elrodc@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
AdvancedHMC = "0bf59076-c3b1-5ca4-86bd-e02cd72cde3d"
CSTParser = "00ebfdb7-1f24-5e51-bd34-a7502290713f"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataDrivenDiffEq = "2445eb08-9709-466a-b3fc-47e12bd697a2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DistributedArrays = "aaf54ef3-cdf8-58ed-94cc-d582ad619b94"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
ExponentialUtilities = "d4d017d3-3776-5f7e-afef-a10c40355c18"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Future = "9fa8497b-333b-5362-9e8d-4d0656e87820"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GlobalSensitivity = "af5da776-676b-467e-8baf-acd8249e4f0f"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
JumpProcesses = "ccbc3e58-028d-4f4c-8cd5-9ae44345cda5"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LabelledArrays = "2ee39098-c373-598a-b85f-a56591580800"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Loess = "4345ca2d-374a-55d4-8d30-97f9976e7612"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MCMCDiagnosticTools = "be115224-59cd-429b-ad48-344e309966f0"
MKL_jll = "856f044c-d86e-5d09-b602-aeab76dc8ba7"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJFlux = "094fc8d1-fd35-5302-93ea-dabda2abf845"
MLJXGBoostInterface = "54119dfa-1dab-4055-a167-80440f4f7a91"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
PSIS = "ce719bf2-d5d0-4fb9-925d-10a81b42ad04"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ParetoSmooth = "a68b5a21-f429-434e-8bfa-46b447300aac"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
ProvenanceBase = "4d266fdc-498f-48d9-a85b-1209f2b17158"
QuantileRegressions = "c6596682-b856-542f-9fff-31404643e889"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReadStatTables = "52522f7a-9570-4e34-8ac6-c005c74d4b84"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
RecursiveTupleMath = "4a4311fe-81ff-4bcc-86a3-5026a4bf5b9f"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RelocatableFolders = "05181044-ff0b-4ac5-8273-598c1e38db00"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SimpleChains = "de6bee2f-e2f4-4ec7-b6ed-219cc6f6e9e5"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StrideArraysCore = "7792a7ef-975c-4747-a70f-980b88e8d1da"
Survival = "8a913413-2070-5976-9d4c-2b364fdc2f7f"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"
TreeViews = "a2a6695c-b41b-5b7d-aed9-dbfdeacea5d7"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
VectorizedRNG = "33b4df10-0173-11e9-2a0c-851a7edac40e"

[compat]
AbstractMCMC = "2, 3"
AdvancedHMC = "0.3"
CSTParser = "3"
CSV = "0.10"
Catalyst = "= 12.3.1"
DataFrames = "1.4"
DataInterpolations = "3.0, 4"
DataStructures = "0.18"
DiffEqBase = "= 6.120.0"
DiffResults = "1.0"
DistributedArrays = "0.6"
Distributions = "0.25.63"
EllipsisNotation = "= 1.7.0"
ExponentialUtilities = "1.18"
FFTW = "1"
FillArrays = "0.13"
FiniteDiff = "2.14"
ForwardDiff = "0.10.23 - 0.10.32"
GLM = "1"
GlobalSensitivity = "= 2.1.3"
Integrals = "3"
JuliaFormatter = "1"
JumpProcesses = "9"
KernelDensity = "0.6"
LabelledArrays = "1.7.1"
Latexify = "0.15.13"
LinearSolve = "1"
Loess = "0.5.3"
MCMCChains = "5.0"
MCMCDiagnosticTools = "0.1"
MLJBase = "0.20, 0.21"
MLJXGBoostInterface = "0.2, 0.3"
MacroTools = "0.5"
Missings = "1.0"
ModelingToolkit = "= 8.38"
NonlinearSolve = "= 1.1.1"
Optim = "1.7.1"
OrdinaryDiffEq = "= 6.47.0"
PDMats = "0.11"
PSIS = "0.5, 0.6"
Parameters = "0.12"
ParetoSmooth = "0.7"
ProgressLogging = "0.1"
ProgressMeter = "1.4"
ProvenanceBase = "0.2"
QuantileRegressions = "0.1.10"
RecursiveArrayTools = "= 2.36.0"
RecursiveTupleMath = "0.1"
Reexport = "1.0"
Roots = "< 1.4.1"
SciMLBase = "= 1.86.2"
SpecialFunctions = "2"
StaticArrays = "1.5.0"
StatsBase = "0.33"
StatsFuns = "1"
Survival = "0.2"
Symbolics = "= 4.13"
Tables = "0.2, 1.0"
ThreadsX = "0.1"
TransformVariables = "0.6, 0.7"
TreeViews = "0.3"
Unitful = "1.0"
VectorizedRNG = "0.2.16"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
